Removed some unecessary code and replaced echo with printf for good practice.

diff --git a/contrib/no/ntnu/pkgbuild/tag b/contrib/no/ntnu/pkgbuild/tag
--- a/contrib/no/ntnu/pkgbuild/tag
+++ b/contrib/no/ntnu/pkgbuild/tag
@@ -8,17 +8,16 @@
 #
 shopt -s extglob
 
-
 base_url=https://cerebrum.svn.sourceforge.net/svnroot/cerebrum
 
 die() {
-    echo "$1"
+    printf '%s\n' "$1" >&2
     exit "${2:-1}"
 }
 
 usage() {
     cat << EOF
-Usage:$0 [-m commit_message] branch [tag]
+Usage: $0 [-m commit_message] branch [tag]
 
     -m commit_message   Set a specific commit-message. Default is "Tagging 
                         <tag> from <branch>."
@@ -46,7 +45,7 @@ branch=$1 tag=$2
 
 [[ $branch ]] || die "Missing branch version" 1
 if [[ -z $tag ]]; then
-    echo "Querying server to find next tag-number..."
+    printf 'Querying server to find next tag version... '
     greatest=0
     while IFS= read -r dir; do
         [[ $dir = "ntnu-prod-$branch".+([0-9])/ ]] || continue
@@ -54,19 +53,18 @@ if [[ -z $tag ]]; then
         (( greatest = tagnum > greatest ? tagnum : greatest ))
     done < <(svn list "$base_url/tags")
     tag=$branch.$((greatest + 1))
+    printf '%s\n' "$tag"
 fi
 
-urls=( "$base_url/branches/ntnu-prod-$branch" "$base_url/tags/ntnu-prod-$tag" )
-commit_msg=${commit_msg:-Tagging $tag from $branch}
 command=( 
     svn copy 
-    -m "$commit_msg"
+    -m "${commit_msg:-Tagging $tag from $branch.}"
     "$base_url/branches/ntnu-prod-$branch"
     "$base_url/tags/ntnu-prod-$tag"
 )
 
-echo "Going to perform the following command:"
-printf "%q " "${command[@]}"; printf '\n'
-echo "Hit Enter or Return to continue, Ctrl-c to abort"
-read || die "Aborted" 2
+printf 'Going to perform the following command:\n'
+printf '%q ' "${command[@]}"; printf '\n'
+read -p "Hit Enter or Return to continue, Ctrl-c to abort. " || die "Aborted" 2
+printf 'Tagging...\n'
 "${command[@]}"
